### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by shawkynasr** [barrer/java-cc-cedict-parser#2]
There are many tags for cc-cedict, like: slang, accounting, sports, etc.

Here is example: [CC-CEDICT 汉英词典 2019.06.19](https://www.pdawiki.com/forum/forum.php?mod=viewthread&tid=11155)

shbf's css so good, can be refrence.

**Comment by barrer** [comment]
@shawkynasr 

Unfortunately, the CC-CEDICT source data does not include such TAGs, which are added by users when they contribute their own interpretations, and there are no specific rules to match these contents.

This feature is easy to implement, but it is very time-consuming to organize all the TAGs and may be missed, and it is also necessary to follow the latest translation in real time.

https://cc-cedict.org/editor/editor.php?handler=QueryDictionary&querydictionary_search=%E4%B8%AD%E5%A4%AE%E7%9B%B4%E8%BD%84%E5%B8%82

**Comment by shawkynasr** [comment]
Yes, I see.
Here some of tags according to shbf file.

updated file. All of tags.

[tags.txt](https://github.com/barrer/java-cc-cedict-parser/files/5689213/tags.txt)
